// Generated by gencpp from file oogway_search_service/service.msg
// DO NOT EDIT!


#ifndef OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICE_H
#define OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <oogway_search_service/serviceRequest.h>
#include <oogway_search_service/serviceResponse.h>


namespace oogway_search_service
{

struct service
{

typedef serviceRequest Request;
typedef serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service
} // namespace oogway_search_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::oogway_search_service::service > {
  static const char* value()
  {
    return "c3f0723336176df636671fb21af3864b";
  }

  static const char* value(const ::oogway_search_service::service&) { return value(); }
};

template<>
struct DataType< ::oogway_search_service::service > {
  static const char* value()
  {
    return "oogway_search_service/service";
  }

  static const char* value(const ::oogway_search_service::service&) { return value(); }
};


// service_traits::MD5Sum< ::oogway_search_service::serviceRequest> should match
// service_traits::MD5Sum< ::oogway_search_service::service >
template<>
struct MD5Sum< ::oogway_search_service::serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::oogway_search_service::service >::value();
  }
  static const char* value(const ::oogway_search_service::serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::oogway_search_service::serviceRequest> should match
// service_traits::DataType< ::oogway_search_service::service >
template<>
struct DataType< ::oogway_search_service::serviceRequest>
{
  static const char* value()
  {
    return DataType< ::oogway_search_service::service >::value();
  }
  static const char* value(const ::oogway_search_service::serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::oogway_search_service::serviceResponse> should match
// service_traits::MD5Sum< ::oogway_search_service::service >
template<>
struct MD5Sum< ::oogway_search_service::serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::oogway_search_service::service >::value();
  }
  static const char* value(const ::oogway_search_service::serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::oogway_search_service::serviceResponse> should match
// service_traits::DataType< ::oogway_search_service::service >
template<>
struct DataType< ::oogway_search_service::serviceResponse>
{
  static const char* value()
  {
    return DataType< ::oogway_search_service::service >::value();
  }
  static const char* value(const ::oogway_search_service::serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICE_H
