// Generated by gencpp from file oogway_search_service/serviceRequest.msg
// DO NOT EDIT!


#ifndef OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICEREQUEST_H
#define OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace oogway_search_service
{
template <class ContainerAllocator>
struct serviceRequest_
{
  typedef serviceRequest_<ContainerAllocator> Type;

  serviceRequest_()
    : angular_velocity(0.0)  {
    }
  serviceRequest_(const ContainerAllocator& _alloc)
    : angular_velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _angular_velocity_type;
  _angular_velocity_type angular_velocity;





  typedef boost::shared_ptr< ::oogway_search_service::serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oogway_search_service::serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serviceRequest_

typedef ::oogway_search_service::serviceRequest_<std::allocator<void> > serviceRequest;

typedef boost::shared_ptr< ::oogway_search_service::serviceRequest > serviceRequestPtr;
typedef boost::shared_ptr< ::oogway_search_service::serviceRequest const> serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oogway_search_service::serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oogway_search_service::serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::oogway_search_service::serviceRequest_<ContainerAllocator1> & lhs, const ::oogway_search_service::serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angular_velocity == rhs.angular_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::oogway_search_service::serviceRequest_<ContainerAllocator1> & lhs, const ::oogway_search_service::serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace oogway_search_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oogway_search_service::serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oogway_search_service::serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oogway_search_service::serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fe6a877ff2aa34e3df952191878f909";
  }

  static const char* value(const ::oogway_search_service::serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fe6a877ff2aa34eULL;
  static const uint64_t static_value2 = 0x3df952191878f909ULL;
};

template<class ContainerAllocator>
struct DataType< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oogway_search_service/serviceRequest";
  }

  static const char* value(const ::oogway_search_service::serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angular_velocity\n"
;
  }

  static const char* value(const ::oogway_search_service::serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oogway_search_service::serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oogway_search_service::serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "angular_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OOGWAY_SEARCH_SERVICE_MESSAGE_SERVICEREQUEST_H
